Add simple-matrix-bot-lib to sdks discover page
matrix-org/matrix.org pull request #1024
Opened 2021-07-17 18:16 UTC by KrazyKirby99999

2021-07-17 18:16 UTC, KrazyKirby99999 commented
Commit 088de58 has an inaccurate description.

2021-07-20 16:24 UTC, MadLittleMods commented
> Commit [088de58](https://github.com/matrix-org/matrix.org/commit/088de5812db01a1860a3b39c9631665a5e8b92fd) has an inaccurate description.

@KrazyKirby99999 I'm confused. You linked the current commit (088de5812db01a1860a3b39c9631665a5e8b92fd) as the one that is inaccurate? Can you update this PR?

2021-07-20 21:55 UTC, KrazyKirby99999 commented
The changes of the commit are correct, but the commit message should be "
Initial simple-matrix-bot-lib discover page". Sorry for the confusion.

2021-07-22 04:11 UTC, MadLittleMods requested changes
Tested it out locally and looks good. Only a small change suggested 🙂

http://localhost:8000/sdks/#simple-matrix-bot-lib
<img width="1208" alt="Screen Shot 2021-07-21 at 11 08 59 PM" src="https://user-images.githubusercontent.com/558581/126588989-baeec7b4-75cb-41ee-a034-f93a507cf272.png">


http://localhost:8000/docs/projects/sdk/simple-matrix-bot-lib
<img width="1286" alt="Screen Shot 2021-07-21 at 11 10 34 PM" src="https://user-images.githubusercontent.com/558581/126588992-9785b677-444e-4178-9527-e8b3dc6807b6.png">

2021-07-22 04:11 UTC, MadLittleMods commented on gatsby/content/projects/sdks/simple-matrix-bot-lib.mdx
> +Simple-Matrix-Bot-Lib is a Python bot library for the Matrix ecosystem built on matrix-nio.
We should add a link here so it's easy for people to reference what is being talked about:

```suggestion
Simple-Matrix-Bot-Lib is a Python bot library for the Matrix ecosystem built on [matrix-nio](https://github.com/poljar/matrix-nio)
```

2021-07-22 13:12 UTC, KrazyKirby99999 commented
The suggestion should be accepted now.

2021-07-22 21:04 UTC, merged

2021-07-22 21:05 UTC, MadLittleMods commented
Merged! Thanks for adding your project @KrazyKirby99999 🐂