Add Minecraft to list of bridges & add EndBridge as first bridge.
matrix-org/matrix.org pull request #2002
Opened 2023-09-04 16:00 UTC by Idriss975

2023-09-04 17:11 UTC, Idriss975 commented
We need to argue about the logo since recently Mojang made some strict rules about using Minecraft assets.

https://www.minecraft.net/en-us/usage-guidelines

2025-09-06 15:52 UTC, HarHarLinks requested changes

2025-09-06 15:52 UTC, HarHarLinks commented on content/ecosystem/bridges/minecraft/bridges.toml
> +docs = "https://gitea.com/Jonah369/EndBridge/wiki"
```suggestion
docs = "https://modrinth.com/mod/endbridge"
```

2025-09-06 15:52 UTC, HarHarLinks commented on content/ecosystem/bridges/minecraft/bridges.toml
> +maturity = "Alpha"
```suggestion
maturity = "Obsolete"
```

2025-09-06 15:52 UTC, HarHarLinks commented on content/ecosystem/bridges/minecraft/logo.svg
this would need to be annotated like https://github.com/fsfe/reuse-tool?tab=readme-ov-file#usage

2026-08-10 20:35 UTC, weeman1337 commented
Closing [according to the contribution guidelines](https://github.com/matrix-org/matrix.org/blob/main/CONTRIBUTING.md#review--publishing-policy), because there were no reply after three weeks

2026-08-10 20:35 UTC, closed without merging