Added Chatrix to clients page
matrix-org/matrix.org pull request #2408
Opened 2024-06-20 10:04 UTC by navyansh007

Added relevant client information for Chatrix on the Clients page of the website. This includes the markdown file containing information about Chatrix and the SVG file for its logo.

2024-06-20 11:51 UTC, HarHarLinks commented
resolves #2213

2024-06-20 14:04 UTC, thibaultamartin commented
@akirk I see the last commit was 2 months ago, is Chatrix maintained :) ?

2024-06-22 19:59 UTC, akirk commented
Well, we'll fix bugs when needed and release updates, but at the moment the features are enough for WordPress.org, so we're not adding any new features for now.

2024-06-24 19:25 UTC, thibaultamartin requested changes

2024-06-25 05:06 UTC, navyansh007 commented on content/ecosystem/clients/chatrix.md
> +multi_language = ""
Hello there, I have made the requested changes in my branch's code. I request you to please have a look at it.

2024-06-26 08:43 UTC, akirk commented
As a bit of evidence :-) we just [released 0.9.1 of Chatrix](https://github.com/Automattic/chatrix/releases/tag/0.9.1).

2024-06-26 09:08 UTC, navyansh007 commented
I have modified the latest release date as well for Chatrix. I request you to please have a look at it.

2024-07-07 16:07 UTC, navyansh007 commented
Hello there @thibaultamartin, it's been around two weeks since I pushed my last changes in the PR. May you please let me know if there is any issue with my PR, that I need to resolve before it can be merged?

2024-08-01 14:31 UTC, MTRNord approved these changes

2024-08-01 14:31 UTC, merged