Enhanced README: Contribution Guidelines, TOC, and Overview
matrix-org/matrix.org pull request #2504
Opened 2024-09-24 17:31 UTC by batramahek

Descriptive Overview: Added a detailed intro about Matrix.org, emphasizing its purpose.
Build Instructions: Provided detailed step-by-step instructions for building the website
Table of Contents: Added a table of contents to make navigation through the various sections easier
Contribution Guidelines: Created a clear section for contribution and added steps for how to start contributing to this open-source project.

2024-09-26 14:13 UTC, MTRNord requested changes

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +cd matrix.org
This seems to not be working with Github Markdown. Could you fix that please? Have a look at the rich diff button on the top right of this file to see how it is being rendered

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +'''
Same as the other comment

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +git checkout -b <yourBranchName>
Same as the other comment

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +4. Submit a pull request (PR)
```suggestion
4. Submit a pull request
```

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +If you have any questions about the project or your contribution, you may join the various community chats on https://matrix.to/#/#matrix.org-website:matrix.org
```suggestion
If you have any questions about the project or your contribution, you may join our room https://matrix.to/#/#matrix.org-website:matrix.org
```

2024-09-26 14:13 UTC, MTRNord commented on README.md
> +Matrix.org is a decentralized, open standard for real-time communication which allows users to collaborate in public and private rooms over IP. Matrix's purpose is to allow users to text and call wit
```suggestion
Matrix.org is an open standard for decentralised, secure communications while also allowing you to bridge to other networks easily.

This Repository covers our main website.

For spec please take a look at https://github.com/matrix-org/matrix-spec
For the conference website take a look at https://github.com/matrix-org/matrix-conf-website
```

2024-12-05 16:17 UTC, thibaultamartin commented
OP didn't reply in 2 months on easy to address comments, and we highly suspect this was generated by a LLM.

2024-12-05 16:17 UTC, closed without merging