Added Link to SDKs from the "Build on Matrix" section
matrix-org/matrix.org pull request #2548
Opened 2024-10-31 04:33 UTC by SjxSubham

Issue #2532 

#### Review the changes, and let me know is this accurate position to add the link? Or should I Add at another line and tell me that exact position

2024-11-07 15:02 UTC, MTRNord requested changes
Hi :) The links end up without the /content part which is in the repository. Therefor that can be removed. Also there is an overview page at /ecosystem so we can drop the sdk. Additionally the docs links does redirect by default and it is slightly better to link tot he correct thing. If you can fix these then we can apply this :)

2024-11-07 15:02 UTC, MTRNord commented on templates/index.html
> +            Matrix is a rich <a style="color:blue;text-decoration:none;" href="/content/ecosystem/sdks">ecosystem</a> of clients, servers, bots and application
```suggestion
            Matrix is a rich <a style="color:blue;text-decoration:none;" href="/ecosystem">ecosystem</a> of clients, servers, bots and application
```

2024-11-07 15:02 UTC, MTRNord commented on templates/index.html
> +            services. Find out more in our <a style="color:blue;text-decoration:none;" href="/docs/matrix-concepts">developer documentation</a>.
```suggestion
            services. Find out more in our <a style="color:blue;text-decoration:none;" href="/docs/matrix-concepts/elements-of-matrix/">developer documentation</a>.
```

2024-11-14 04:33 UTC, SjxSubham commented
@MTRNord Check the resolved changes... and let me know if any more changes are needed...

2024-12-05 15:07 UTC, thibaultamartin requested changes
Please don't rely on `style` attributes directly in the html

2026-09-09 01:40 UTC, awtj8o81ryywg793 commented
Whilst I’m aware that you never received the review you requested, I can also see that you did not address the [review](https://github.com/matrix-org/matrix.org/pull/2548#pullrequestreview-2481984277) posted on 05/12/2024. Instead, you pushed a single commit that does not fix the issues highlighted in the review. Due to the time that has passed without a follow-up addressing these issues, I’m closing this pull request in line with our policy in `CONTRIBUTING.md`. See: https://github.com/matrix-org/matrix.org/blob/main/CONTRIBUTING.md#review--publishing-policy.

2026-09-09 01:40 UTC, closed without merging